# ===============
# Header
# ===============
menu:
  首页: /
  归档: /archives
banner: "images/banner.jpg"
subtitle:
links:
  github: https://github.com/lqy978599280

# ===============
# Content
# ===============
excerpt_link: 阅读全文
fancybox: true

# ===============
# Footer
# ===============
copyright:

# ===============
# Sidebar
# ===============
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# ===============
# Widget behavior
# ===============
archive_type: 'monthly'
show_count: false
recent_posts_limits: 5

# ===============
# Miscellaneous
# ===============
google_analytics:
gauges_analytics:
favicon: /favicon.png
twitter:
fb_admins:
fb_app_id:

# ===============
# Comment system
# ===============
disqus_shortname:
valine:
  enable: false
  appId:
  appKey:
  notify: false
  verify: false
  pageSize: 10
  avatar: mm
  lang: zh-cn
  placeholder: 写下你的想法...
  guest_info: nick,mail,link
